name: xplr
title: xplr
version: git
summary: A hackable, minimal, fast TUI file explorer
description: |
  xplr is a hackable, minimal, fast TUI file explorer, giving you a terminal
  interface to explore your filesystem, and perform batch operations efficiently.
source-code: https://github.com/sayanarijit/xplr
issues: https://github.com/sayanarijit/xplr/issues
website: https://xplr.dev
license: MIT
contact: xplr@arijitbasu.in

base: core22
grade: stable
confinement: strict

parts:
  xplr:
    plugin: rust
    source: .
    build-packages:
      - liblua5.1-0-dev
      - libluajit-5.1-dev
      - pkg-config
      - gcc
      - make

apps:
  xplr:
    command: bin/xplr
    plugs:
      - home
      - removable-media
      - network
